#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Reflow Gateway — Quick Install Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/JulianPedro/reflow-gateway/main/install.sh | bash
#   # or
#   bash install.sh
# ─────────────────────────────────────────────────────────────

REPO_URL="https://github.com/JulianPedro/reflow-gateway.git"
INSTALL_DIR="reflow-gateway"
HEALTH_URL="http://localhost:3000/health"
HEALTH_TIMEOUT=60

# ── Colors (only if stdout is a terminal) ──
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  BOLD='\033[1m'
  NC='\033[0m'
else
  GREEN='' YELLOW='' RED='' BOLD='' NC=''
fi

info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }
fatal() { error "$@"; exit 1; }

# ── 1. Check prerequisites ──
info "Checking prerequisites..."

command -v git  >/dev/null 2>&1 || fatal "git is required but not installed"
command -v curl >/dev/null 2>&1 || fatal "curl is required but not installed"

# Docker
command -v docker >/dev/null 2>&1 || fatal "docker is required but not installed"
docker info >/dev/null 2>&1     || fatal "Docker daemon is not running"

# Docker Compose (v2 plugin or standalone v1)
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fatal "docker compose is required but not installed"
fi

info "Using: $COMPOSE"

# ── 2. Clone or update repo ──
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Repository already exists, pulling latest changes..."
  git -C "$INSTALL_DIR" pull --ff-only || warn "git pull failed, continuing with existing code"
else
  info "Cloning repository..."
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── 3. Generate .env ──
generate_random() {
  local length=$1
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$length"
  else
    # Fallback to /dev/urandom
    head -c "$length" /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c "$(( length * 2 ))"
  fi
}

generate_alnum() {
  local length=$1
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c "$length"
  else
    head -c 256 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c "$length"
  fi
}

if [ -f .env ]; then
  info ".env already exists, skipping generation (delete .env to regenerate)"
else
  info "Generating .env with random secrets..."

  DB_PASSWORD="$(generate_random 16)"
  JWT_SECRET="$(generate_random 32)"
  ENCRYPTION_KEY="$(generate_alnum 32)"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Database
DB_PASSWORD=${DB_PASSWORD}

# JWT Secret
JWT_SECRET=${JWT_SECRET}

# Encryption key for token storage (exactly 32 characters)
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Frontend API URL
NEXT_PUBLIC_API_URL=http://localhost:3000
EOF

  info ".env created with random secrets"
fi

# ── 4. Create config.yaml from example (if not present) ──
if [ -f config.yaml ]; then
  info "config.yaml already exists, skipping"
else
  info "Creating config.yaml from config.yaml.example..."
  cp config.yaml.example config.yaml
fi

# ── 5. Start services ──
info "Starting services with $COMPOSE..."
$COMPOSE up -d

# ── 6. Wait for health check ──
info "Waiting for gateway to be healthy (timeout: ${HEALTH_TIMEOUT}s)..."

elapsed=0
while [ "$elapsed" -lt "$HEALTH_TIMEOUT" ]; do
  if curl -sf "$HEALTH_URL" >/dev/null 2>&1; then
    info "Gateway is healthy!"
    break
  fi
  sleep 2
  elapsed=$((elapsed + 2))
done

if [ "$elapsed" -ge "$HEALTH_TIMEOUT" ]; then
  warn "Health check timed out after ${HEALTH_TIMEOUT}s"
  warn "Services may still be starting. Check: $COMPOSE logs"
fi

# ── 7. Print status ──
printf "\n"
printf "${BOLD}════════════════════════════════════════════════${NC}\n"
printf "${BOLD}  Reflow Gateway is running!${NC}\n"
printf "${BOLD}════════════════════════════════════════════════${NC}\n"
printf "\n"
printf "  Gateway API:   ${GREEN}http://localhost:3000${NC}\n"
printf "  API Docs:      ${GREEN}http://localhost:3000/docs${NC}\n"
printf "  Grafana:       ${GREEN}http://localhost:3002${NC}  (admin/admin)\n"
printf "\n"
printf "  Register the first admin user:\n"
printf "\n"
printf "    curl -X POST http://localhost:3000/api/auth/register \\ \n"
printf "      -H 'Content-Type: application/json' \\ \n"
printf "      -d '{\"email\":\"admin@example.com\",\"password\":\"secure123\"}'\n"
printf "\n"
printf "${BOLD}════════════════════════════════════════════════${NC}\n"
